# -*- coding: utf-8 -*-

from . import last_update_pricelist_date,composite_products,assign_picking_updated,web_odoo_warehouse_config_fields,warehouse_picking_stock,verification_service_closures,inches_field,negative_quantitys_picking,autocomplete_picking_from_ot_code,product_name_location_list